//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 11:22:59 AM EAT 
//


package com.enat.multiAccountAPI.wsdl.batch;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FCUBS_HEADER" type="{http://fcubs.ofss.com/service/FCUBSDEService}FCUBS_HEADERType"/&gt;
 *         &lt;element name="FCUBS_BODY"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Detms-Jrnl-Tmpl-Master-Full" type="{http://fcubs.ofss.com/service/FCUBSDEService}MultiJrnlTeml-Full-Type"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fcubsheader",
    "fcubsbody"
})
@XmlRootElement(name = "DELETEMJRNLTEMPLATE_FSFS_REQ")
public class DELETEMJRNLTEMPLATEFSFSREQ {

    @XmlElement(name = "FCUBS_HEADER", required = true)
    protected FCUBSHEADERType fcubsheader;
    @XmlElement(name = "FCUBS_BODY", required = true)
    protected DELETEMJRNLTEMPLATEFSFSREQ.FCUBSBODY fcubsbody;

    /**
     * Gets the value of the fcubsheader property.
     * 
     * @return
     *     possible object is
     *     {@link FCUBSHEADERType }
     *     
     */
    public FCUBSHEADERType getFCUBSHEADER() {
        return fcubsheader;
    }

    /**
     * Sets the value of the fcubsheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link FCUBSHEADERType }
     *     
     */
    public void setFCUBSHEADER(FCUBSHEADERType value) {
        this.fcubsheader = value;
    }

    /**
     * Gets the value of the fcubsbody property.
     * 
     * @return
     *     possible object is
     *     {@link DELETEMJRNLTEMPLATEFSFSREQ.FCUBSBODY }
     *     
     */
    public DELETEMJRNLTEMPLATEFSFSREQ.FCUBSBODY getFCUBSBODY() {
        return fcubsbody;
    }

    /**
     * Sets the value of the fcubsbody property.
     * 
     * @param value
     *     allowed object is
     *     {@link DELETEMJRNLTEMPLATEFSFSREQ.FCUBSBODY }
     *     
     */
    public void setFCUBSBODY(DELETEMJRNLTEMPLATEFSFSREQ.FCUBSBODY value) {
        this.fcubsbody = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Detms-Jrnl-Tmpl-Master-Full" type="{http://fcubs.ofss.com/service/FCUBSDEService}MultiJrnlTeml-Full-Type"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "detmsJrnlTmplMasterFull"
    })
    public static class FCUBSBODY {

        @XmlElement(name = "Detms-Jrnl-Tmpl-Master-Full", required = true)
        protected MultiJrnlTemlFullType detmsJrnlTmplMasterFull;

        /**
         * Gets the value of the detmsJrnlTmplMasterFull property.
         * 
         * @return
         *     possible object is
         *     {@link MultiJrnlTemlFullType }
         *     
         */
        public MultiJrnlTemlFullType getDetmsJrnlTmplMasterFull() {
            return detmsJrnlTmplMasterFull;
        }

        /**
         * Sets the value of the detmsJrnlTmplMasterFull property.
         * 
         * @param value
         *     allowed object is
         *     {@link MultiJrnlTemlFullType }
         *     
         */
        public void setDetmsJrnlTmplMasterFull(MultiJrnlTemlFullType value) {
            this.detmsJrnlTmplMasterFull = value;
        }

    }

}
