//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 11:22:59 AM EAT 
//


package com.enat.multiAccountAPI.wsdl.batch;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MultiJrnlBook-Full-Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultiJrnlBook-Full-Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="REFERENCE_NO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BATCH_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CURR_NO" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="TEMPLATE_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VALUE_DATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="BRANCH_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TOTAL_DR" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="TOTAL_CR" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="MAKER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MAKDTTIME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CHECHKERID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CHKDTTIME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AUTHSTAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TXNSTAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Detbs-Jrnl-Txn-Detail" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SERIAL_NO" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                   &lt;element name="USER_REF_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="DR_CR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="BRANCH_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ACORGL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="CCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="TXN_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="INSTRUMENT_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="LCY_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="ADDL_TEXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ACDESC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CUSTOMER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="EXCH_RATE" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Detbs-Batch-Master" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="BATCH_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="DEBIT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="CREDIT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="DR_ENT_TOTAL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="CR_ENT_TOTAL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Devws-Batch-Master" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="BATCH_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="LAST_OPERATED_BY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="LAST_AUTHORISED_BY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="MAKERDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                   &lt;element name="CHECKERDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                   &lt;element name="DEBIT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="CREDIT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="BALANCING" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Misdetails" type="{http://fcubs.ofss.com/service/FCUBSDEService}TxnMIS-Full-Type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiJrnlBook-Full-Type", propOrder = {
    "referenceno",
    "batchno",
    "currno",
    "templatecode",
    "valuedate",
    "branchcode",
    "ccy",
    "totaldr",
    "totalcr",
    "maker",
    "makdttime",
    "chechkerid",
    "chkdttime",
    "authstat",
    "txnstat",
    "detbsJrnlTxnDetail",
    "detbsBatchMaster",
    "devwsBatchMaster",
    "misdetails"
})
public class MultiJrnlBookFullType {

    @XmlElement(name = "REFERENCE_NO", required = true)
    protected String referenceno;
    @XmlElement(name = "BATCH_NO")
    protected String batchno;
    @XmlElement(name = "CURR_NO")
    protected BigDecimal currno;
    @XmlElement(name = "TEMPLATE_CODE")
    protected String templatecode;
    @XmlElement(name = "VALUE_DATE")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar valuedate;
    @XmlElement(name = "BRANCH_CODE")
    protected String branchcode;
    @XmlElement(name = "CCY")
    protected String ccy;
    @XmlElement(name = "TOTAL_DR")
    protected BigDecimal totaldr;
    @XmlElement(name = "TOTAL_CR")
    protected BigDecimal totalcr;
    @XmlElement(name = "MAKER")
    protected String maker;
    @XmlElement(name = "MAKDTTIME")
    protected String makdttime;
    @XmlElement(name = "CHECHKERID")
    protected String chechkerid;
    @XmlElement(name = "CHKDTTIME")
    protected String chkdttime;
    @XmlElement(name = "AUTHSTAT")
    protected String authstat;
    @XmlElement(name = "TXNSTAT")
    protected String txnstat;
    @XmlElement(name = "Detbs-Jrnl-Txn-Detail")
    protected List<MultiJrnlBookFullType.DetbsJrnlTxnDetail> detbsJrnlTxnDetail;
    @XmlElement(name = "Detbs-Batch-Master")
    protected MultiJrnlBookFullType.DetbsBatchMaster detbsBatchMaster;
    @XmlElement(name = "Devws-Batch-Master")
    protected MultiJrnlBookFullType.DevwsBatchMaster devwsBatchMaster;
    @XmlElement(name = "Misdetails")
    protected TxnMISFullType misdetails;

    /**
     * Gets the value of the referenceno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFERENCENO() {
        return referenceno;
    }

    /**
     * Sets the value of the referenceno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFERENCENO(String value) {
        this.referenceno = value;
    }

    /**
     * Gets the value of the batchno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBATCHNO() {
        return batchno;
    }

    /**
     * Sets the value of the batchno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBATCHNO(String value) {
        this.batchno = value;
    }

    /**
     * Gets the value of the currno property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCURRNO() {
        return currno;
    }

    /**
     * Sets the value of the currno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCURRNO(BigDecimal value) {
        this.currno = value;
    }

    /**
     * Gets the value of the templatecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEMPLATECODE() {
        return templatecode;
    }

    /**
     * Sets the value of the templatecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEMPLATECODE(String value) {
        this.templatecode = value;
    }

    /**
     * Gets the value of the valuedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVALUEDATE() {
        return valuedate;
    }

    /**
     * Sets the value of the valuedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVALUEDATE(XMLGregorianCalendar value) {
        this.valuedate = value;
    }

    /**
     * Gets the value of the branchcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBRANCHCODE() {
        return branchcode;
    }

    /**
     * Sets the value of the branchcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBRANCHCODE(String value) {
        this.branchcode = value;
    }

    /**
     * Gets the value of the ccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCY() {
        return ccy;
    }

    /**
     * Sets the value of the ccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCY(String value) {
        this.ccy = value;
    }

    /**
     * Gets the value of the totaldr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTOTALDR() {
        return totaldr;
    }

    /**
     * Sets the value of the totaldr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTOTALDR(BigDecimal value) {
        this.totaldr = value;
    }

    /**
     * Gets the value of the totalcr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTOTALCR() {
        return totalcr;
    }

    /**
     * Sets the value of the totalcr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTOTALCR(BigDecimal value) {
        this.totalcr = value;
    }

    /**
     * Gets the value of the maker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAKER() {
        return maker;
    }

    /**
     * Sets the value of the maker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAKER(String value) {
        this.maker = value;
    }

    /**
     * Gets the value of the makdttime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAKDTTIME() {
        return makdttime;
    }

    /**
     * Sets the value of the makdttime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAKDTTIME(String value) {
        this.makdttime = value;
    }

    /**
     * Gets the value of the chechkerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHECHKERID() {
        return chechkerid;
    }

    /**
     * Sets the value of the chechkerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHECHKERID(String value) {
        this.chechkerid = value;
    }

    /**
     * Gets the value of the chkdttime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHKDTTIME() {
        return chkdttime;
    }

    /**
     * Sets the value of the chkdttime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHKDTTIME(String value) {
        this.chkdttime = value;
    }

    /**
     * Gets the value of the authstat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHSTAT() {
        return authstat;
    }

    /**
     * Sets the value of the authstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHSTAT(String value) {
        this.authstat = value;
    }

    /**
     * Gets the value of the txnstat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTXNSTAT() {
        return txnstat;
    }

    /**
     * Sets the value of the txnstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTXNSTAT(String value) {
        this.txnstat = value;
    }

    /**
     * Gets the value of the detbsJrnlTxnDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detbsJrnlTxnDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetbsJrnlTxnDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultiJrnlBookFullType.DetbsJrnlTxnDetail }
     * 
     * 
     */
    public List<MultiJrnlBookFullType.DetbsJrnlTxnDetail> getDetbsJrnlTxnDetail() {
        if (detbsJrnlTxnDetail == null) {
            detbsJrnlTxnDetail = new ArrayList<MultiJrnlBookFullType.DetbsJrnlTxnDetail>();
        }
        return this.detbsJrnlTxnDetail;
    }

    /**
     * Gets the value of the detbsBatchMaster property.
     * 
     * @return
     *     possible object is
     *     {@link MultiJrnlBookFullType.DetbsBatchMaster }
     *     
     */
    public MultiJrnlBookFullType.DetbsBatchMaster getDetbsBatchMaster() {
        return detbsBatchMaster;
    }

    /**
     * Sets the value of the detbsBatchMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiJrnlBookFullType.DetbsBatchMaster }
     *     
     */
    public void setDetbsBatchMaster(MultiJrnlBookFullType.DetbsBatchMaster value) {
        this.detbsBatchMaster = value;
    }

    /**
     * Gets the value of the devwsBatchMaster property.
     * 
     * @return
     *     possible object is
     *     {@link MultiJrnlBookFullType.DevwsBatchMaster }
     *     
     */
    public MultiJrnlBookFullType.DevwsBatchMaster getDevwsBatchMaster() {
        return devwsBatchMaster;
    }

    /**
     * Sets the value of the devwsBatchMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiJrnlBookFullType.DevwsBatchMaster }
     *     
     */
    public void setDevwsBatchMaster(MultiJrnlBookFullType.DevwsBatchMaster value) {
        this.devwsBatchMaster = value;
    }

    /**
     * Gets the value of the misdetails property.
     * 
     * @return
     *     possible object is
     *     {@link TxnMISFullType }
     *     
     */
    public TxnMISFullType getMisdetails() {
        return misdetails;
    }

    /**
     * Sets the value of the misdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnMISFullType }
     *     
     */
    public void setMisdetails(TxnMISFullType value) {
        this.misdetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="BATCH_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="DEBIT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="CREDIT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="DR_ENT_TOTAL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="CR_ENT_TOTAL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "batchno",
        "description",
        "debit",
        "credit",
        "drenttotal",
        "crenttotal"
    })
    public static class DetbsBatchMaster {

        @XmlElement(name = "BATCH_NO")
        protected String batchno;
        @XmlElement(name = "DESCRIPTION")
        protected String description;
        @XmlElement(name = "DEBIT")
        protected BigDecimal debit;
        @XmlElement(name = "CREDIT")
        protected BigDecimal credit;
        @XmlElement(name = "DR_ENT_TOTAL")
        protected BigDecimal drenttotal;
        @XmlElement(name = "CR_ENT_TOTAL")
        protected BigDecimal crenttotal;

        /**
         * Gets the value of the batchno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBATCHNO() {
            return batchno;
        }

        /**
         * Sets the value of the batchno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBATCHNO(String value) {
            this.batchno = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDESCRIPTION() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDESCRIPTION(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the debit property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDEBIT() {
            return debit;
        }

        /**
         * Sets the value of the debit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDEBIT(BigDecimal value) {
            this.debit = value;
        }

        /**
         * Gets the value of the credit property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCREDIT() {
            return credit;
        }

        /**
         * Sets the value of the credit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCREDIT(BigDecimal value) {
            this.credit = value;
        }

        /**
         * Gets the value of the drenttotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDRENTTOTAL() {
            return drenttotal;
        }

        /**
         * Sets the value of the drenttotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDRENTTOTAL(BigDecimal value) {
            this.drenttotal = value;
        }

        /**
         * Gets the value of the crenttotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCRENTTOTAL() {
            return crenttotal;
        }

        /**
         * Sets the value of the crenttotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCRENTTOTAL(BigDecimal value) {
            this.crenttotal = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SERIAL_NO" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *         &lt;element name="USER_REF_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="DR_CR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="BRANCH_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ACORGL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="CCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="TXN_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="INSTRUMENT_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="LCY_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="ADDL_TEXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ACDESC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CUSTOMER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="EXCH_RATE" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "serialno",
        "userrefno",
        "drcr",
        "branchcode",
        "acorgl",
        "account",
        "amount",
        "ccy",
        "txncode",
        "instrumentno",
        "lcyamount",
        "addltext",
        "acdesc",
        "customer",
        "exchrate"
    })
    public static class DetbsJrnlTxnDetail {

        @XmlElement(name = "SERIAL_NO", required = true)
        protected BigDecimal serialno;
        @XmlElement(name = "USER_REF_NO")
        protected String userrefno;
        @XmlElement(name = "DR_CR")
        protected String drcr;
        @XmlElement(name = "BRANCH_CODE")
        protected String branchcode;
        @XmlElement(name = "ACORGL")
        protected String acorgl;
        @XmlElement(name = "ACCOUNT")
        protected String account;
        @XmlElement(name = "AMOUNT")
        protected BigDecimal amount;
        @XmlElement(name = "CCY")
        protected String ccy;
        @XmlElement(name = "TXN_CODE")
        protected String txncode;
        @XmlElement(name = "INSTRUMENT_NO")
        protected String instrumentno;
        @XmlElement(name = "LCY_AMOUNT")
        protected BigDecimal lcyamount;
        @XmlElement(name = "ADDL_TEXT")
        protected String addltext;
        @XmlElement(name = "ACDESC")
        protected String acdesc;
        @XmlElement(name = "CUSTOMER")
        protected String customer;
        @XmlElement(name = "EXCH_RATE")
        protected BigDecimal exchrate;

        /**
         * Gets the value of the serialno property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSERIALNO() {
            return serialno;
        }

        /**
         * Sets the value of the serialno property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSERIALNO(BigDecimal value) {
            this.serialno = value;
        }

        /**
         * Gets the value of the userrefno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSERREFNO() {
            return userrefno;
        }

        /**
         * Sets the value of the userrefno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSERREFNO(String value) {
            this.userrefno = value;
        }

        /**
         * Gets the value of the drcr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDRCR() {
            return drcr;
        }

        /**
         * Sets the value of the drcr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDRCR(String value) {
            this.drcr = value;
        }

        /**
         * Gets the value of the branchcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBRANCHCODE() {
            return branchcode;
        }

        /**
         * Sets the value of the branchcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBRANCHCODE(String value) {
            this.branchcode = value;
        }

        /**
         * Gets the value of the acorgl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACORGL() {
            return acorgl;
        }

        /**
         * Sets the value of the acorgl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACORGL(String value) {
            this.acorgl = value;
        }

        /**
         * Gets the value of the account property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACCOUNT() {
            return account;
        }

        /**
         * Sets the value of the account property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACCOUNT(String value) {
            this.account = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAMOUNT() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAMOUNT(BigDecimal value) {
            this.amount = value;
        }

        /**
         * Gets the value of the ccy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCCY() {
            return ccy;
        }

        /**
         * Sets the value of the ccy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCCY(String value) {
            this.ccy = value;
        }

        /**
         * Gets the value of the txncode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTXNCODE() {
            return txncode;
        }

        /**
         * Sets the value of the txncode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTXNCODE(String value) {
            this.txncode = value;
        }

        /**
         * Gets the value of the instrumentno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINSTRUMENTNO() {
            return instrumentno;
        }

        /**
         * Sets the value of the instrumentno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINSTRUMENTNO(String value) {
            this.instrumentno = value;
        }

        /**
         * Gets the value of the lcyamount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getLCYAMOUNT() {
            return lcyamount;
        }

        /**
         * Sets the value of the lcyamount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setLCYAMOUNT(BigDecimal value) {
            this.lcyamount = value;
        }

        /**
         * Gets the value of the addltext property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getADDLTEXT() {
            return addltext;
        }

        /**
         * Sets the value of the addltext property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setADDLTEXT(String value) {
            this.addltext = value;
        }

        /**
         * Gets the value of the acdesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACDESC() {
            return acdesc;
        }

        /**
         * Sets the value of the acdesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACDESC(String value) {
            this.acdesc = value;
        }

        /**
         * Gets the value of the customer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCUSTOMER() {
            return customer;
        }

        /**
         * Sets the value of the customer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCUSTOMER(String value) {
            this.customer = value;
        }

        /**
         * Gets the value of the exchrate property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getEXCHRATE() {
            return exchrate;
        }

        /**
         * Sets the value of the exchrate property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setEXCHRATE(BigDecimal value) {
            this.exchrate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="BATCH_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="LAST_OPERATED_BY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="LAST_AUTHORISED_BY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="MAKERDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *         &lt;element name="CHECKERDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *         &lt;element name="DEBIT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="CREDIT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="BALANCING" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "batchnumber",
        "description",
        "lastoperatedby",
        "lastauthorisedby",
        "makerdt",
        "checkerdt",
        "debit",
        "credit",
        "balancing"
    })
    public static class DevwsBatchMaster {

        @XmlElement(name = "BATCH_NUMBER", required = true)
        protected String batchnumber;
        @XmlElement(name = "DESCRIPTION")
        protected String description;
        @XmlElement(name = "LAST_OPERATED_BY")
        protected String lastoperatedby;
        @XmlElement(name = "LAST_AUTHORISED_BY")
        protected String lastauthorisedby;
        @XmlElement(name = "MAKERDT")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar makerdt;
        @XmlElement(name = "CHECKERDT")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar checkerdt;
        @XmlElement(name = "DEBIT")
        protected BigDecimal debit;
        @XmlElement(name = "CREDIT")
        protected BigDecimal credit;
        @XmlElement(name = "BALANCING")
        protected String balancing;

        /**
         * Gets the value of the batchnumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBATCHNUMBER() {
            return batchnumber;
        }

        /**
         * Sets the value of the batchnumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBATCHNUMBER(String value) {
            this.batchnumber = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDESCRIPTION() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDESCRIPTION(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the lastoperatedby property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLASTOPERATEDBY() {
            return lastoperatedby;
        }

        /**
         * Sets the value of the lastoperatedby property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLASTOPERATEDBY(String value) {
            this.lastoperatedby = value;
        }

        /**
         * Gets the value of the lastauthorisedby property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLASTAUTHORISEDBY() {
            return lastauthorisedby;
        }

        /**
         * Sets the value of the lastauthorisedby property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLASTAUTHORISEDBY(String value) {
            this.lastauthorisedby = value;
        }

        /**
         * Gets the value of the makerdt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getMAKERDT() {
            return makerdt;
        }

        /**
         * Sets the value of the makerdt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setMAKERDT(XMLGregorianCalendar value) {
            this.makerdt = value;
        }

        /**
         * Gets the value of the checkerdt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCHECKERDT() {
            return checkerdt;
        }

        /**
         * Sets the value of the checkerdt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCHECKERDT(XMLGregorianCalendar value) {
            this.checkerdt = value;
        }

        /**
         * Gets the value of the debit property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDEBIT() {
            return debit;
        }

        /**
         * Sets the value of the debit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDEBIT(BigDecimal value) {
            this.debit = value;
        }

        /**
         * Gets the value of the credit property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCREDIT() {
            return credit;
        }

        /**
         * Sets the value of the credit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCREDIT(BigDecimal value) {
            this.credit = value;
        }

        /**
         * Gets the value of the balancing property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBALANCING() {
            return balancing;
        }

        /**
         * Sets the value of the balancing property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBALANCING(String value) {
            this.balancing = value;
        }

    }

}
