//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.16 at 03:12:07 PM EAT 
//


package com.enat.multiAccountAPI.wsdl.batch;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MultiJrnlTeml-Modify-IO-Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultiJrnlTeml-Modify-IO-Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TEMPLATE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MODNO" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="Detms-Jrnl-Tmpl-Detail" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TEMPLATE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="SERIAL_NO" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                   &lt;element name="DR_CR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ACORGL_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="AC_GL_NO1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="TXN_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ADDL_TEXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CUST_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="BRANCH_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiJrnlTeml-Modify-IO-Type", propOrder = {
    "templatecode",
    "description",
    "modno",
    "detmsJrnlTmplDetail"
})
public class MultiJrnlTemlModifyIOType {

    @XmlElement(name = "TEMPLATE_CODE", required = true)
    protected String templatecode;
    @XmlElement(name = "DESCRIPTION")
    protected String description;
    @XmlElement(name = "MODNO")
    protected BigInteger modno;
    @XmlElement(name = "Detms-Jrnl-Tmpl-Detail")
    protected List<MultiJrnlTemlModifyIOType.DetmsJrnlTmplDetail> detmsJrnlTmplDetail;

    /**
     * Gets the value of the templatecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEMPLATECODE() {
        return templatecode;
    }

    /**
     * Sets the value of the templatecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEMPLATECODE(String value) {
        this.templatecode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the modno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMODNO() {
        return modno;
    }

    /**
     * Sets the value of the modno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMODNO(BigInteger value) {
        this.modno = value;
    }

    /**
     * Gets the value of the detmsJrnlTmplDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detmsJrnlTmplDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetmsJrnlTmplDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultiJrnlTemlModifyIOType.DetmsJrnlTmplDetail }
     * 
     * 
     */
    public List<MultiJrnlTemlModifyIOType.DetmsJrnlTmplDetail> getDetmsJrnlTmplDetail() {
        if (detmsJrnlTmplDetail == null) {
            detmsJrnlTmplDetail = new ArrayList<MultiJrnlTemlModifyIOType.DetmsJrnlTmplDetail>();
        }
        return this.detmsJrnlTmplDetail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TEMPLATE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="SERIAL_NO" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *         &lt;element name="DR_CR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ACORGL_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="AC_GL_NO1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="TXN_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ADDL_TEXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CUST_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="BRANCH_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "templatecode",
        "serialno",
        "drcr",
        "acorglno",
        "acglno1",
        "txncode",
        "addltext",
        "ccy",
        "custno",
        "branchcode"
    })
    public static class DetmsJrnlTmplDetail {

        @XmlElement(name = "TEMPLATE_CODE", required = true)
        protected String templatecode;
        @XmlElement(name = "SERIAL_NO", required = true)
        protected BigDecimal serialno;
        @XmlElement(name = "DR_CR")
        protected String drcr;
        @XmlElement(name = "ACORGL_NO")
        protected String acorglno;
        @XmlElement(name = "AC_GL_NO1")
        protected String acglno1;
        @XmlElement(name = "TXN_CODE")
        protected String txncode;
        @XmlElement(name = "ADDL_TEXT")
        protected String addltext;
        @XmlElement(name = "CCY")
        protected String ccy;
        @XmlElement(name = "CUST_NO")
        protected String custno;
        @XmlElement(name = "BRANCH_CODE")
        protected String branchcode;

        /**
         * Gets the value of the templatecode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTEMPLATECODE() {
            return templatecode;
        }

        /**
         * Sets the value of the templatecode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTEMPLATECODE(String value) {
            this.templatecode = value;
        }

        /**
         * Gets the value of the serialno property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSERIALNO() {
            return serialno;
        }

        /**
         * Sets the value of the serialno property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSERIALNO(BigDecimal value) {
            this.serialno = value;
        }

        /**
         * Gets the value of the drcr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDRCR() {
            return drcr;
        }

        /**
         * Sets the value of the drcr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDRCR(String value) {
            this.drcr = value;
        }

        /**
         * Gets the value of the acorglno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACORGLNO() {
            return acorglno;
        }

        /**
         * Sets the value of the acorglno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACORGLNO(String value) {
            this.acorglno = value;
        }

        /**
         * Gets the value of the acglno1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACGLNO1() {
            return acglno1;
        }

        /**
         * Sets the value of the acglno1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACGLNO1(String value) {
            this.acglno1 = value;
        }

        /**
         * Gets the value of the txncode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTXNCODE() {
            return txncode;
        }

        /**
         * Sets the value of the txncode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTXNCODE(String value) {
            this.txncode = value;
        }

        /**
         * Gets the value of the addltext property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getADDLTEXT() {
            return addltext;
        }

        /**
         * Sets the value of the addltext property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setADDLTEXT(String value) {
            this.addltext = value;
        }

        /**
         * Gets the value of the ccy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCCY() {
            return ccy;
        }

        /**
         * Sets the value of the ccy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCCY(String value) {
            this.ccy = value;
        }

        /**
         * Gets the value of the custno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCUSTNO() {
            return custno;
        }

        /**
         * Sets the value of the custno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCUSTNO(String value) {
            this.custno = value;
        }

        /**
         * Gets the value of the branchcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBRANCHCODE() {
            return branchcode;
        }

        /**
         * Sets the value of the branchcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBRANCHCODE(String value) {
            this.branchcode = value;
        }

    }

}
