
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.generate-ddl=true
spring.main.allow-bean-definition-overriding=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver 
spring.jpa.hibernate.ddl-auto=update 
spring.datasource.jdbc-url=jdbc:sqlserver://localhost:1433;instanceName=EBSQLSRV;encrypt=false;databaseName=cdasdsad;
spring.datasource.password=skdjcsaj
spring.datasource.username=test
application.allowedOrigin=[http://localhost:6000]
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost
eureka.client.serviceUrl.defaultZone=${localhost}
services.hr=http://localhost
client.account-uri=http://localhost/FCUBSAccService
client.batch-uri=http://localhoste/FCUBSDEService
derash.url=https://api.qa.derash.gov.et/agent/customer-bill-data
client.maker-user=slkjsa
client.authorizer-user=""
client.user.name=kasdlsaj
client.user.password=""

cron.expression=0 0/30 8-10 * * MON-SAT
cron.pending=0 0/60 8-10 * * MON-SAT
