//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 11:22:54 AM EAT 
//


package com.enat.multiAccountAPI.wsdl.account;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;


/**
 * <p>Java class for Autodepdetails-Full-Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Autodepdetails-Full-Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BRN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ACC" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Autodepdetails" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DEPACCCLS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ACCCCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SWPAMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="CUSTOMER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="DEPCCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SEQNO" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="SWPTOAC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="XREF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="MINREQDBAL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="SWPMULTIOF" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="RETRYTILLDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                   &lt;element name="SWPTOACBRN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="STARTDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                   &lt;element name="DEPTENYEARS" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="MONTHS" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="DAYS" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Autodepdetails-Full-Type", propOrder = {
    "brn",
    "acc",
    "autodepdetails"
})
public class AutodepdetailsFullType {

    @XmlElement(name = "BRN")
    protected String brn;
    @XmlElement(name = "ACC", required = true)
    protected String acc;
    @XmlElement(name = "Autodepdetails")
    protected AutodepdetailsFullType.Autodepdetails autodepdetails;

    /**
     * Gets the value of the brn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBRN() {
        return brn;
    }

    /**
     * Sets the value of the brn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBRN(String value) {
        this.brn = value;
    }

    /**
     * Gets the value of the acc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACC() {
        return acc;
    }

    /**
     * Sets the value of the acc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACC(String value) {
        this.acc = value;
    }

    /**
     * Gets the value of the autodepdetails property.
     * 
     * @return
     *     possible object is
     *     {@link AutodepdetailsFullType.Autodepdetails }
     *     
     */
    public AutodepdetailsFullType.Autodepdetails getAutodepdetails() {
        return autodepdetails;
    }

    /**
     * Sets the value of the autodepdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutodepdetailsFullType.Autodepdetails }
     *     
     */
    public void setAutodepdetails(AutodepdetailsFullType.Autodepdetails value) {
        this.autodepdetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DEPACCCLS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ACCCCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SWPAMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="CUSTOMER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="DEPCCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SEQNO" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="SWPTOAC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="XREF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="MINREQDBAL" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="SWPMULTIOF" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="RETRYTILLDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *         &lt;element name="SWPTOACBRN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="STARTDT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *         &lt;element name="DEPTENYEARS" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="MONTHS" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="DAYS" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "depacccls",
        "accccy",
        "swpamount",
        "customer",
        "depccy",
        "seqno",
        "swptoac",
        "scode",
        "xref",
        "minreqdbal",
        "swpmultiof",
        "retrytilldt",
        "swptoacbrn",
        "startdt",
        "deptenyears",
        "months",
        "days"
    })
    public static class Autodepdetails {

        @XmlElement(name = "DEPACCCLS")
        protected String depacccls;
        @XmlElement(name = "ACCCCY")
        protected String accccy;
        @XmlElement(name = "SWPAMOUNT")
        protected BigDecimal swpamount;
        @XmlElement(name = "CUSTOMER")
        protected String customer;
        @XmlElement(name = "DEPCCY")
        protected String depccy;
        @XmlElement(name = "SEQNO")
        protected BigDecimal seqno;
        @XmlElement(name = "SWPTOAC")
        protected String swptoac;
        @XmlElement(name = "SCODE")
        protected String scode;
        @XmlElement(name = "XREF")
        protected String xref;
        @XmlElement(name = "MINREQDBAL")
        protected BigDecimal minreqdbal;
        @XmlElement(name = "SWPMULTIOF")
        protected BigDecimal swpmultiof;
        @XmlElement(name = "RETRYTILLDT")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar retrytilldt;
        @XmlElement(name = "SWPTOACBRN")
        protected String swptoacbrn;
        @XmlElement(name = "STARTDT")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar startdt;
        @XmlElement(name = "DEPTENYEARS")
        protected BigDecimal deptenyears;
        @XmlElement(name = "MONTHS")
        protected BigDecimal months;
        @XmlElement(name = "DAYS")
        protected BigDecimal days;

        /**
         * Gets the value of the depacccls property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDEPACCCLS() {
            return depacccls;
        }

        /**
         * Sets the value of the depacccls property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDEPACCCLS(String value) {
            this.depacccls = value;
        }

        /**
         * Gets the value of the accccy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACCCCY() {
            return accccy;
        }

        /**
         * Sets the value of the accccy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACCCCY(String value) {
            this.accccy = value;
        }

        /**
         * Gets the value of the swpamount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSWPAMOUNT() {
            return swpamount;
        }

        /**
         * Sets the value of the swpamount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSWPAMOUNT(BigDecimal value) {
            this.swpamount = value;
        }

        /**
         * Gets the value of the customer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCUSTOMER() {
            return customer;
        }

        /**
         * Sets the value of the customer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCUSTOMER(String value) {
            this.customer = value;
        }

        /**
         * Gets the value of the depccy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDEPCCY() {
            return depccy;
        }

        /**
         * Sets the value of the depccy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDEPCCY(String value) {
            this.depccy = value;
        }

        /**
         * Gets the value of the seqno property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSEQNO() {
            return seqno;
        }

        /**
         * Sets the value of the seqno property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSEQNO(BigDecimal value) {
            this.seqno = value;
        }

        /**
         * Gets the value of the swptoac property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSWPTOAC() {
            return swptoac;
        }

        /**
         * Sets the value of the swptoac property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSWPTOAC(String value) {
            this.swptoac = value;
        }

        /**
         * Gets the value of the scode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSCODE() {
            return scode;
        }

        /**
         * Sets the value of the scode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSCODE(String value) {
            this.scode = value;
        }

        /**
         * Gets the value of the xref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXREF() {
            return xref;
        }

        /**
         * Sets the value of the xref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXREF(String value) {
            this.xref = value;
        }

        /**
         * Gets the value of the minreqdbal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMINREQDBAL() {
            return minreqdbal;
        }

        /**
         * Sets the value of the minreqdbal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMINREQDBAL(BigDecimal value) {
            this.minreqdbal = value;
        }

        /**
         * Gets the value of the swpmultiof property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSWPMULTIOF() {
            return swpmultiof;
        }

        /**
         * Sets the value of the swpmultiof property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSWPMULTIOF(BigDecimal value) {
            this.swpmultiof = value;
        }

        /**
         * Gets the value of the retrytilldt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getRETRYTILLDT() {
            return retrytilldt;
        }

        /**
         * Sets the value of the retrytilldt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setRETRYTILLDT(XMLGregorianCalendar value) {
            this.retrytilldt = value;
        }

        /**
         * Gets the value of the swptoacbrn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSWPTOACBRN() {
            return swptoacbrn;
        }

        /**
         * Sets the value of the swptoacbrn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSWPTOACBRN(String value) {
            this.swptoacbrn = value;
        }

        /**
         * Gets the value of the startdt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getSTARTDT() {
            return startdt;
        }

        /**
         * Sets the value of the startdt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setSTARTDT(XMLGregorianCalendar value) {
            this.startdt = value;
        }

        /**
         * Gets the value of the deptenyears property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDEPTENYEARS() {
            return deptenyears;
        }

        /**
         * Sets the value of the deptenyears property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDEPTENYEARS(BigDecimal value) {
            this.deptenyears = value;
        }

        /**
         * Gets the value of the months property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMONTHS() {
            return months;
        }

        /**
         * Sets the value of the months property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMONTHS(BigDecimal value) {
            this.months = value;
        }

        /**
         * Gets the value of the days property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDAYS() {
            return days;
        }

        /**
         * Sets the value of the days property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDAYS(BigDecimal value) {
            this.days = value;
        }

    }

}
