//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.16 at 03:11:59 PM EAT 
//


package com.enat.multiAccountAPI.wsdl.account;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for VirAcc-Create-IO-Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VirAcc-Create-IO-Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AC_NO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="VIRTUAL_ACC_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="VIRTUAL_ACC_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="VIRTUAL_ACC_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="VIRTUAL_ACC_OPEN_DT" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="ACC_CURR" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DEFACC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UDFDETAILS" type="{http://fcubs.ofss.com/service/FCUBSAccService}UDFDETAILSType2" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VirAcc-Create-IO-Type", propOrder = {
    "acno",
    "virtualacccode",
    "virtualaccnumber",
    "virtualaccname",
    "virtualaccopendt",
    "acccurr",
    "defacc",
    "udfdetails"
})
public class VirAccCreateIOType {

    @XmlElement(name = "AC_NO", required = true)
    protected String acno;
    @XmlElement(name = "VIRTUAL_ACC_CODE", required = true)
    protected String virtualacccode;
    @XmlElement(name = "VIRTUAL_ACC_NUMBER", required = true)
    protected String virtualaccnumber;
    @XmlElement(name = "VIRTUAL_ACC_NAME", required = true)
    protected String virtualaccname;
    @XmlElement(name = "VIRTUAL_ACC_OPEN_DT", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar virtualaccopendt;
    @XmlElement(name = "ACC_CURR", required = true)
    protected String acccurr;
    @XmlElement(name = "DEFACC")
    protected String defacc;
    @XmlElement(name = "UDFDETAILS")
    protected List<UDFDETAILSType2> udfdetails;

    /**
     * Gets the value of the acno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACNO() {
        return acno;
    }

    /**
     * Sets the value of the acno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACNO(String value) {
        this.acno = value;
    }

    /**
     * Gets the value of the virtualacccode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVIRTUALACCCODE() {
        return virtualacccode;
    }

    /**
     * Sets the value of the virtualacccode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVIRTUALACCCODE(String value) {
        this.virtualacccode = value;
    }

    /**
     * Gets the value of the virtualaccnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVIRTUALACCNUMBER() {
        return virtualaccnumber;
    }

    /**
     * Sets the value of the virtualaccnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVIRTUALACCNUMBER(String value) {
        this.virtualaccnumber = value;
    }

    /**
     * Gets the value of the virtualaccname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVIRTUALACCNAME() {
        return virtualaccname;
    }

    /**
     * Sets the value of the virtualaccname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVIRTUALACCNAME(String value) {
        this.virtualaccname = value;
    }

    /**
     * Gets the value of the virtualaccopendt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVIRTUALACCOPENDT() {
        return virtualaccopendt;
    }

    /**
     * Sets the value of the virtualaccopendt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVIRTUALACCOPENDT(XMLGregorianCalendar value) {
        this.virtualaccopendt = value;
    }

    /**
     * Gets the value of the acccurr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCCURR() {
        return acccurr;
    }

    /**
     * Sets the value of the acccurr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCCURR(String value) {
        this.acccurr = value;
    }

    /**
     * Gets the value of the defacc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEFACC() {
        return defacc;
    }

    /**
     * Sets the value of the defacc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEFACC(String value) {
        this.defacc = value;
    }

    /**
     * Gets the value of the udfdetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the udfdetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUDFDETAILS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UDFDETAILSType2 }
     * 
     * 
     */
    public List<UDFDETAILSType2> getUDFDETAILS() {
        if (udfdetails == null) {
            udfdetails = new ArrayList<UDFDETAILSType2>();
        }
        return this.udfdetails;
    }

}
